version: '3.8'

services:
    app:
        build:
            context: .
        container_name: laravel_app
        volumes:
            - .:/var/www
        ports:
            - "9000:9000"
        depends_on:
            - mysql

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: laravel_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
